from typing import Final


ACCOUNTS: Final = "accounts"
MEMBERS: Final = "users"
PROFILES: Final = "profiles"
VISITS: Final = "visits"
APPOINTMENTS: Final = "appointments"
RECORDS: Final = "records"
PATIENTS: Final = "patients"
DIAGNOSIS: Final = "diagnosis"
BLOODPRESSURES: Final = "bloodpressures"
HEARTRATES: Final = "heartrates"
RESPIRATORYRATES: Final = "respiratoryrates"
BODYTEMPERATURES: Final = "bodytemperatures"
BODYWEIGHTS: Final = "bodyweights"
HEIGHTS: Final = "heights"
BODYMASSINDEX: Final = "bmi"
FAMILYHISTORY: Final = "familyhistory"
HOSPITALIZATIONHISTORY: Final = "hospitalizations"
MEDICALHISTROY: Final = "medicalhistory"
MEDICATIONS: Final = "medications"
OBHISTROY: Final = "obhistory"
SURGICALHISTORY: Final = "surgicalhistory"
ALLERGY: Final = "allergies"
IMMUNIZATION: Final = "immunizations"
