ACCOUNTS = "accounts"
MEMBERS = "members"
<<<<<<< HEAD
=======
PROFILES = "profiles"
>>>>>>> 25c02d6 (refactor)
VISITS = "visits"
APPOINTMENTS = "appointments"
RECORDS = "records"
PATIENTS = "patients"
DIAGNOSIS = "diagnosis"
BLOODPRESSURES = "bloodpressures"
HEARTRATES = "heartrates"
RESPIRATORYRATES = "respiratoryrates"
BODYTEMPERATURES = "bodytemperatures"
BODYWEIGHTS = "bodyweights"
HEIGHTS = "heights"
BODYMASSINDEX = "bmi"
FAMILYHISTORY = "familyhistory"
HOSPITALIZATIONHISTORY = "hospitalizations"
MEDICALHISTROY = "medicalhistory"
MEDICATIONS = "medications"
OBHISTROY = "obhistory"
SURGICALHISTORY = "surgicalhistory"
